<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
    <PackageReference Include="Onyx.Shared.Contracts" Version="1.0.2" />
    <PackageReference Include="Onyx.Shared.Enums" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Onyx.Domain\Onyx.Service.Domain\Onyx.Service.Domain.csproj" />
    <ProjectReference Include="..\..\Onyx.Infrastructure\Onyx.Service.Infrastructure\Onyx.Service.Infrastructure.csproj" />
  </ItemGroup>

</Project>
